application-properties:
  security:
    issuer-server: ${ISSUER_SERVER:http://localhost:8080}
    token-delivery: ${TOKEN_DELIVERY:COOKIE}
    signing-key: ${SIGNING_KEY:ed25519} # Lowercase
    no-auth-urls:
      - "/auth/**"
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
      - "/health"
  bootstrap:
    peer-database: ${BOOTSTRAP_PEER_DATABASE:true}
spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/spring-base-auth}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}
  liquibase:
    enabled: false
  jpa.open-in-view: false
  threads.virtual.enabled: true
decorator.datasource.p6spy:
  logging: CUSTOM
  custom-appender-class: com.vulinh.utils.MyP6SpyLogging
management.endpoints.web:
  base-path: '/'
  exposure.include: health
